### ISSUE TITLE
Unable to Sign in - TypeError: t.contains is not a function

### ISSUE THREAD

**Issue by nisola-c4** [microsoft/vscode-pull-request-github#3692]
- Extension version: 0.46.0
- VSCode Version: 1.68.1
- OS: Windows 10 Pro 21H2

Steps to Reproduce:

1. Press "Sign in" button
2. Observe "Error signing in to GitHub" toast message

Output:

> [Info] Error signing in to GitHub: TypeError: t.contains is not a function
[Info] TypeError: t.contains is not a function
	at f1.setCurrentUser (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.46.0\dist\extension.js:1111:16459)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f1.createHub (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.46.0\dist\extension.js:1111:17854)
	at async f1.login (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.46.0\dist\extension.js:1111:15547)
	at async gm.authenticate (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.46.0\dist\extension.js:1227:18011)
	at async c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.46.0\dist\extension.js:1227:6624
	at async o._executeContributedCommand (c:\Users\nisola\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:62513)

Troubleshooting steps completed:

- Uninstalled all other extensions
- Uninstalled/Reinstalled GitHub Pull Requests and Issues extenstion
- Uninstall/Reinstall of VSCode
- Uninstall VSCode, delete %UserProfile%/.vscode directory, reinstall VSCode
- Clear cache and cookies for Github in both Edge and Chrome

**Comment by tofupup** [comment]
I'm seeing this, as well, but running WSL2 Ubuntu:

- Extension version: 0.46.0
- VSCode Version: 1.69.2
- OS: Windows 10 Pro 21H2 - WSL2 Ubuntu 20.04

Log output:


```
[Info] Error signing in to GitHub: TypeError: t.contains is not a function
[Info] TypeError: t.contains is not a function
	at f1.setCurrentUser (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.0/dist/extension.js:1111:16459)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f1.createHub (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.0/dist/extension.js:1111:17854)
	at async f1.login (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.0/dist/extension.js:1111:15547)
	at async gm.authenticate (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.0/dist/extension.js:1227:18011)
	at async /home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.0/dist/extension.js:1227:6624
	at async o._executeContributedCommand (/home/john/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:62863)

```

**Comment by tofupup** [comment]
Thank you for the quick patch, I switched to the pre-release version, but unfortunately still get an error around that catch statement.

```
[Info] Error signing in to GitHub: TypeError: t.message.contains is not a function
[Info] TypeError: t.message.contains is not a function
	at S1.setCurrentUser (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1148:16986)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S1.createHub (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1148:18319)
	at async S1.login (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1148:15989)
	at async Sm.authenticate (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1265:18461)
	at async /home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1265:6905
	at async o._executeContributedCommand (/home/john/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:62863)
```

Please let me know if I should open a separate issue.

**Comment by nisola-c4** [comment]
I switched to a pre-release build as well (v0.47.2022072509) and am still getting an error as well.

> [Info] Authentication> Error setting the user Bad credentials.
[Info] Error signing in to GitHub: TypeError: t.message.contains is not a function
[Info] TypeError: t.message.contains is not a function
	at S1.setCurrentUser (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.47.2022072509\dist\extension.js:1148:16986)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S1.createHub (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.47.2022072509\dist\extension.js:1148:18319)
	at async S1.login (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.47.2022072509\dist\extension.js:1148:15989)
	at async Sm.authenticate (c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.47.2022072509\dist\extension.js:1265:18461)
	at async c:\Users\nisola\.vscode\extensions\github.vscode-pull-request-github-0.47.2022072509\dist\extension.js:1265:6905
	at async o._executeContributedCommand (c:\Users\nisola\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:62863)

**Comment by tofupup** [comment]
I've resolved this, at least for now, by removing my github authentication stored Windows credentials.

- Exit VSCode
- Remove the stored credential

```
PS C:\Users\john> cmdkey /list:vscodevscode.github-authentication/github.auth

Currently stored credentials for vscodevscode.github-authentication/github.auth:

    Target: vscodevscode.github-authentication/github.auth
    Type: Generic
    User: github.auth

PS C:\Users\john> cmdkey /delete:vscodevscode.github-authentication/github.auth

CMDKEY: Credential deleted successfully.
```

- Start VSCode and reauth to github

I'm not sure what was wrong with the stored credentials, but hopefully this will help others move past this if you're running in to it.

**Comment by alexr00** [comment]
@tofupup thank you for posting your work around! I've removed the code that's having this issue and the change will be in the pre-release build in the next 3 hours.

**Comment by tofupup** [comment]
@alexr00 Appreciate your quick work on this!  I took at look at the patch, and from my limited knowledge it looks like it may still have the issue shown in the second logs @nisola-c4 and I posted above.  It passes the e.message existence check, but in the case we were having, e.message.contains isn't a function.

I was using the pre-release extension for the second logs, which I think already had this patch integrated at the time I installed it.  Unfortunately, I got it working, so wasn't able to double check.

I messed with this some more, and have been able to get it fail in a repeatable fashion (maybe needs to be running on Windows or WSL to use the Windows credentials, not sure if this would happen on a  pure linux system).  It looks like it's related to Windows credentials having a github authentication key set, but the GitHub for VS Code oauth app has been revoked:

- From fresh VSCode, with Windows credential key removed ( cmdkey /delete:vscodevscode.github-authentication/github.auth ), open Github pull requests and allow auth to github
- Verify it's working
- Stop VSCode
- On https://github.com/settings/applications revoke the "GitHub for VS Code" application
- Start VSCode and open Github Pull Requests extension and try to use the login button again
- Notice "Error signing in to Github" pops up, and logs show:

```
[Info] TypeError: t.message.contains is not a function
	at S1.setCurrentUser (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1148:16986)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S1.createHub (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1148:18319)
	at async S1.login (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1148:15989)
	at async Sm.authenticate (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1265:18461)
	at async /home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072509/dist/extension.js:1265:6905
	at async o._executeContributedCommand (/home/john/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:62863)
```

Hope this helps, let me know if you need any further info.

**Comment by tofupup** [comment]
Also tested with the newly released 0.46.1 version, which still displays the issue:

```
[Info] Error signing in to GitHub: TypeError: t.message.contains is not a function
[Info] TypeError: t.message.contains is not a function
	at f1.setCurrentUser (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.1/dist/extension.js:1111:16544)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f1.createHub (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.1/dist/extension.js:1111:17877)
	at async f1.login (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.1/dist/extension.js:1111:15547)
	at async gm.authenticate (/home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.1/dist/extension.js:1227:18011)
	at async /home/john/.vscode-server/extensions/github.vscode-pull-request-github-0.46.1/dist/extension.js:1227:6624
	at async o._executeContributedCommand (/home/john/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:62863)
```

**Comment by alexr00** [comment]
@tofupup 0.46.1 doesn't have the fix, so I would expect the issue to continue there. 

What version of the pre-release build were you using? Only the very latest has the fix.

**Comment by tofupup** [comment]
@alexr00 I apologize, I didn't notice that my VSCode wasn't updating to the 0.47.2022072609 version.  It would show that version at the top when installing the prerelease, but it would keep installing 0.47.2022072509.  After downloading the VSIX it looks like 0.47.2022072609 will not work with 1.69.2, it requires the VSCode Insiders.

I installed 0.47.2022072609 on Insiders, and you are correct, the error now references that we have bad credentials:

```
[Info] Error signing in to GitHub: HttpError: Bad credentials
[Info] HttpError: Bad credentials
	at /home/john/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.47.2022072609/dist/extension.js:1131:6173
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async S1.setCurrentUser (/home/john/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.47.2022072609/dist/extension.js:1148:16819)
	at async S1.createHub (/home/john/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.47.2022072609/dist/extension.js:1148:18000)
	at async S1.login (/home/john/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.47.2022072609/dist/extension.js:1148:15989)
	at async Sm.authenticate (/home/john/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.47.2022072609/dist/extension.js:1265:18461)
	at async /home/john/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.47.2022072609/dist/extension.js:1265:6905
	at async a._executeContributedCommand (/home/john/.vscode-server-insiders/bin/cc098faebd320a2eea3da6ae154b7e2e1347a4b9/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)
```

It doesn't pop up the ability to reauth with Github as if using it the first time, but the definitely the initial error is gone at this point.  Sorry for the confusion!
