### ISSUE TITLE
empty content since vscode v1.50

### ISSUE THREAD

**Issue by hbinkle** [microsoft/vscode-pull-request-github#2206]
- Extension version: 0.15.0 (needed because of **gh enterprise**)
- VSCode Version: 1.50.0
- OS: win10

Since the vscode update from 1.49 to 1.50 the extension shows no longer any content and so can't be used:
![image](https://user-images.githubusercontent.com/51942180/95560834-1accf800-0a1a-11eb-8295-04ef79a07664.png)

**Comment by CommandBlock6417** [comment]
Same issue in macOS Big Sur Beta 9
VScode v1.50
Extension v0.20.1

**Comment by danhendrix** [comment]
Same issue in macOS Catalina 10.15.7. In the developer tools console I see this:

```Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChange is not a function.```

**Comment by CommandBlock6417** [comment]
Looking at my console I see this error when I run "GitHub Pull Requests: Configure":
`Command 'GitHub Pull Requests: Configure...' resulted in an error (command 'pr.configurePRViewlet' not found)`
I also get a `Activating extension 'GitHub.vscode-pull-request-github' failed: Bad credentials.` but I cannot seem to be able to change my credentials since the extension is not working properly.

**Comment by ggcatu** [comment]
Same here, sadly this was the only option left to use this with GHE

**Comment by marci32** [comment]
Same here... I really would be open to any solution to be able to keep using 0.15.0 but downgrading vscode as well is just not acceptable.

**Comment by clogic-sichoi** [comment]
Same here..

**Comment by jnials** [comment]
I've pretty much given up on this extension and gone back to the command line with gh-cli https://cli.github.com/

**Comment by maxned** [comment]
Same issue. I only use the old version of the extension because of enterprise support there. It really disappoints me that the newest VS Code version breaks it. At least before I could keep using the old version but now that the workaround has disappeared, it's extremely frustrating.

**Comment by dincer-cci** [comment]
Same here. 

```Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

> Activating extension 'GitHub.vscode-pull-request-github' failed: Bad credentials.

![image](https://user-images.githubusercontent.com/57612504/98091593-aeb5a680-1e96-11eb-9387-2b31271bd50e.png)

**Comment by coroa** [comment]
I was having the same problem with extension version `0.20.0` just now, which is the latest version from openvsx at them moment. ie. empty panel and in the dev tools:
```
Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChange is not a function.
```

This bug has been fixed by minor release: `0.20.1`, which has not been published on openvsx yet.

**Comment by hbinkle** [comment]
> I was having the same problem with extension version `0.20.0` just now, which is the latest version from openvsx at them moment. ie. empty panel and in the dev tools:
> 
> ```
> Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChange is not a function.
> ```
> 
> This bug has been fixed by minor release: `0.20.1`, which has not been published on openvsx yet and the issue should likely be closed.

I don't know what mean. This issue applies to non github.com connections. --> Connections to selfhosted github enterprise servers. 
Additionally meanwhile v0.20.1 can be retreived through the vs-code marketplace but does not fix the auth proplem of this thread even when manually adding
```json
"githubPullRequests.hosts": [
		{
			"host": "https://my.github-enterprise-server.com/",
			"username": "myuser",
			"token": "MYTOKEN"
		}
	],
```
to the config.

**Comment by coroa** [comment]
Then maybe there are two bug reports intermingled here: I was having the described issues as soon as i switched to 0.50:
1.  github pull requests panel stayed empty, and as
2. @Devnol said it also appeared in 0.20.0, and @danhendrix added in https://github.com/microsoft/vscode-pull-request-github/issues/2206#issuecomment-706213809, the `t.onDidChange` error message.

To be clear, it did apply to connections to github.com for me, and my company uses gitlab so can't test with an enterprise server.

When I updated to 0.20.1 manually from the marketplace, it started working again.

I don't see any mention about GH enterprise server in your bug report other than this is why you are forced to use a very old extensions version of 0.15.0.

So, just for the sake of closure: It might just be that you could get a running 0.15.1 version by cherry-picking the commits from https://github.com/microsoft/vscode-pull-request-github/compare/0.20.0...release/0.20 over to 0.15.0.

**Comment by Devnol** [comment]
The release notes for extension v0.20.1 states clearly that the issue was fixed, so it's normal if it started working gain for you. I tried it now myself and it indeed appears to be working again.

**Comment by coroa** [comment]
> So, just for the sake of closure: It might just be that you could get a running 0.15.1 version by cherry-picking the commits from [0.20.0...release/0.20](https://github.com/microsoft/vscode-pull-request-github/compare/0.20.0...release/0.20) over to 0.15.0.

Worth noting on that idea, that a rebase applies cleanly except for a naming conflict in one place, but it would take me longer than i have beef in it to figure out whether this can be made to work.

**Comment by RMacfarlane** [comment]
@burkeholland Can you create a new issue for this, and include any output in the console when you run "Developer: Open Webview Developer Tools" while this blank view is open?

**Comment by alexr00** [comment]
Haven't seen this in a while, so closing. Please comment with logs from the console and "GitHub Pull Request" if you see again.

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3022
